# Site settings
title: Light & Free Escapes
locale: uk
partner:
  name: Light & Free
  link: http://www.lightandfree.com/

description: >
  Take the leap into the unknown. We’ve partnered with Light & Free to bring you eight deliciously secret staycations, matched to eight equally delicious flavours from the Light & Free range. So if you’re ready to throw yourself into an escape filled with adventure, grab your pack of Light & Free to be in with a chance of winning!

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/uk/2020/lightandfree" # the subpath of your site, e.g. /blog/
img:     "/uk/2020/lightandfree/_assets/img"
css:     "/uk/2020/lightandfree/_assets/css"
js:      "/uk/2020/lightandfree/_assets/js"

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed